name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * *'
  
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE: "False"
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_UPDATED_DATE : "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
